name: steam-charging-eta
on:
  push:
    branches: [main]
    paths: ['steam-charging-eta/**', 'oci/**', '.github/workflows/steam-charging-eta.yml', '.github/workflows/_package-image.yml', 'toolchain.env']
  workflow_dispatch:
permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  build:
    uses: ./.github/workflows/_package-image.yml
    secrets: inherit
    with:
      package: steam-charging-eta
